title: Deep Work Monk
description: A site dedicated to deep work and productivity
url: "https://deepworkmonk.com"
# baseurl: "/DeepWorkMonkWebsite"

# Build settings
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Posts with future dates will be published
future: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - README.md

# Default permalink structure for posts
permalink: /blogs/:title/